apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task3pvc-httpd
  labels:
    name: task3-pvc-httpd
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: htmlos
  labels:
    app: task3label-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
       app: html
  template:
    metadata:
     name: myweb-pod-httpd
     labels:
       app: html
    spec:
      containers:
      - name: task3pod-httpd
        image: httpd
        volumeMounts:
        - name: task3vol-httpd
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: task3vol-httpd
        persistentVolumeClaim:
          claimName: task3pvc-httpd
---
apiVersion: v1
kind: Service
metadata:
  name: task3service-httpd
  labels:
    app: task3label-httpd
spec:
  selector:
    app: html
  type: NodePort
  ports:
    - nodePort: 30001
      port: 82
      targetPort: 80
